aliases:
  bpa: BiblioPixelAnimations.strip
  cl: christmas_lights
  cls: christmas_lights.streamer
  cla: christmas_lights.animations
  fade: christmas_lights.animations.ExponentialFade

run:
  fps: 30
  seconds: 10000000000

animation:
  typename: sequence

numbers: float
layout: strip
